# Pull Node 12 Image.
FROM node:12

# Labels and Credits
LABEL \
    name="NodeJS Hello World as Dev Env" \
    author="Rémi Lavedrine <remi@github.com>" \
    maintainer="Rémi Lavedrine <remi@github.com>" \
    description="The Dockerfile that makes it available to develop a NodeJS HelloWorld app within a Container."

WORKDIR /root/home

EXPOSE 3000

RUN npm install

# Copy source files from host computer to the container
COPY . .

# Update everything required & Install zsh as the default shell within the container.
RUN apt update -y && apt install -y --no-install-recommends \
    gcc \
    git \
    zsh && \
    chsh -s /usr/bin/zsh

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.1/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p sudo \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

# Pour Builder l'image Docker
# docker build . -t helloworldjs

# Pour lancer le container Docker
# docker run -it -p 3000:3000 helloworldjs:latest